### ISSUE TITLE
Too many warnings

### ISSUE THREAD

**Issue by zxdong262** [tylerlong/manate#6]
If user already set the max depth, maybe we should remove the console.warn, or warn only when debug option enabled
![Screen Shot 2024-12-09 at 14 51 14](https://github.com/user-attachments/assets/02794c19-2890-4c03-be01-53dfc46b1a87)

**Comment by tylerlong** [comment]
Are you running React 19?  It is a known issue.  For now I will stay with React 18. 19 is too new to spend time on.

Show me a minimum project to reproduce the issue.

**Comment by zxdong262** [comment]
> Are you running React 19? It is a known issue. For now I will stay with React 18. 19 is too new to spend time on.
> 
> Show me a minimum project to reproduce the issue.

No, not 19, I mean when use it like "manage(new Store(), 1)", no need warn user

**Comment by tylerlong** [comment]
Fixed.
https://github.com/tylerlong/manate/blob/main/test/max-depth.spec.ts
